version: '3.8'

services:
  web-secure-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    networks:
      - secure-net
    depends_on:
      - java-app

  java-app:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - secure-net

networks:
  secure-net:
