SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecPcreMatchLimit 100000
SecPcreMatchLimitRecursion 100000

SecRule ARGS "@rx attack" \
    "id:1234,phase:2,deny,log,msg:'Detected possible attack pattern in request'"

SecRule REQUEST_HEADERS:User-Agent "curl" \
    "id:1235,phase:1,deny,status:403,msg:'Curl detected in User-Agent'"

SecRule IP:REQUESTS "@gt 10" \
    "id:9001,phase:1,drop,msg:'Too many requests from this IP'";


